kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
  #creating mysql in expense namespace
  namespace: expense
  #thus labels are deployment related labels
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector: 
    matchLabels:
      component: frontend
      tier: web
      project: expense
  #pod defintion
  template:
    metadata:
      labels:
        component: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: 637423540068.dkr.ecr.us-east-1.amazonaws.com/expense-frontend:{{ .Values.deployment.imageVersion}}  #ecr expense-frontend(repo)
        # mounting volume nginx-conf
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
      # envFrom:
      # - configMapRef:
      #     name: frontend
      volumes:
      - name: nginx-conf
        configMap:
          name: frontend
          items:
          - key: nginx.conf
            path: nginx.conf